### ISSUE TITLE
Add proper `User-Agent` header to HTTP Requests

### ISSUE THREAD

**Issue by hierynomus** [StackVista/stackstate-cli#52]
### Problem
Currently when monitoring HTTP requests, it is hard to distinguish the different kind of clients connecting to StackState. In order to better distinguish the CLI from other requests, add a proper `User-Agent` header to the requests performed from the CLI

### Solution
Add the following `User-Agent` header: `StackState CLI v<version>` to all HTTP requests

**Comment by craffit** [comment]
@hierynomus @Idorobots one nitpick, there is actually a predefined format for the user agent field w.r.t product/version, would be good to follow that: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

**Comment by hierynomus** [comment]
Ok, agreed @craffit :)

Reopening it, please change it to: `StackStateCLI/<version>` which is in line with the specs posted.

**Comment by Idorobots** [comment]
Good call, guys. :+1:
